
using System.Collections;
using System.Collections.Generic;
using System;
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

/// <summary>
/// Generates a safe wrapper for Tags.
/// </summary>
public static class Tags
{
public static readonly string Untagged = "Untagged";
public static readonly string Respawn = "Respawn";
public static readonly string Finish = "Finish";
public static readonly string EditorOnly = "EditorOnly";
public static readonly string MainCamera = "MainCamera";
public static readonly string Player = "Player";
public static readonly string GameController = "GameController";
}

public enum Layers
{
Default = 0,
TransparentFX = 1,
IgnoreRaycast = 2,
Water = 4,
UI = 5,
Walls = 8,
Nodes = 9,
Bullets = 10,
}

public static class OrbLists
{

static readonly Dictionary<Type, Func<IList>> dict = new Dictionary<Type, Func<IList>>();

public static IList Create(Type t) => dict[t]();

static OrbLists()
{
dict[typeof(Gravity)] = ()=> new List< Gravity>();
dict[typeof(ForceMove)] = ()=> new List< ForceMove>();
dict[typeof(Shooter)] = ()=> new List< Shooter>();
dict[typeof(HueShifter)] = ()=> new List< HueShifter>();
dict[typeof(IDrawOrb)] = ()=> new List< IDrawOrb>();
dict[typeof(IAffectSelfOrb)] = ()=> new List< IAffectSelfOrb>();
dict[typeof(IAffectOtherOrb)] = ()=> new List< IAffectOtherOrb>();
dict[typeof(IFixedAffectOther)] = ()=> new List< IFixedAffectOther>();
dict[typeof(IFixedAffectSelf)] = ()=> new List< IFixedAffectSelf>();
dict[typeof(IAimedActionOrb)] = ()=> new List< IAimedActionOrb>();
dict[typeof(IActionOrb)] = ()=> new List< IActionOrb>();
dict[typeof(IMovementOrb)] = ()=> new List< IMovementOrb>();
dict[typeof(Bomb)] = ()=> new List< Bomb>();
dict[typeof(Player)] = ()=> new List< Player>();

}
}