
using System.Collections;
using System.Collections.Generic;
using System;
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

/// <summary>
/// Generates a safe wrapper for Tags.
/// </summary>

public static class Tags
{
	public static readonly string Untagged = "Untagged";
	public static readonly string Respawn = "Respawn";
	public static readonly string Finish = "Finish";
	public static readonly string EditorOnly = "EditorOnly";
	public static readonly string MainCamera = "MainCamera";
	public static readonly string Player = "Player";
	public static readonly string GameController = "GameController";
	public static readonly string T1 = "T1";
	public static readonly string T2 = "T2";

}

public enum Layers
{
	Default = 0,
	TransparentFX = 0,
	IgnoreRaycast = 0,
	Water = 0,
	UI = 0,
	Walls = 0,
	Nodes = 0,
	Bullets = 0,
	Upper = 0,

}